// The domain events the 34 modules publish, taken from the catalog in
// docs/prd/58-background-jobs-and-events.md.
//
// A name is a fact that already happened: lower case, dot separated, past tense in the last
// segment. A name is permanent. When a payload changes, the envelope `version` goes to 2; the
// event is never renamed, because a consumer written months ago still subscribes to the old name.

/** Every event name the platform publishes, in catalog order. */
export const DOMAIN_EVENTS = [
  // Platform and People Events
  'auth.login.succeeded',
  'auth.login.failed',
  'auth.account.locked',
  'auth.otp.requested',
  'auth.password.reset_requested',
  'auth.password.changed',
  'auth.contact.verified',
  'auth.mfa.enabled',
  'auth.mfa.disabled',
  'auth.session.revoked',
  'auth.token.reuse_detected',
  'invitation.sent',
  'invitation.resent',
  'invitation.revoked',
  'invitation.expired',
  'invitation.accepted',
  'user.created',
  'user.updated',
  'user.suspended',
  'user.activated',
  'user.deactivated',
  'user.deleted',
  'user.password.reset_by_admin',
  'user.mfa.reset',
  'user.sessions.revoked',
  'user.roles.changed',
  'user.campuses.changed',
  'role.created',
  'role.updated',
  'role.deleted',
  'role.permissions.changed',
  'metrics.snapshot.computed',
  'organization.created',
  'organization.verified',
  'organization.onboarding.completed',
  'organization.activated',
  'organization.updated',
  'organization.ownership.transferred',
  'organization.suspended',
  'organization.reactivated',
  'organization.cancelled',
  'organization.limit.near',
  'organization.limit.reached',
  'subscription.trial.ending',
  'subscription.trial.expired',
  'subscription.activated',
  'subscription.plan_changed',
  'subscription.renewed',
  'subscription.payment_failed',
  'subscription.past_due',
  'subscription.cancelled',
  'subscription.invoice.issued',
  'subscription.invoice.paid',
  'subscription.invoice.refunded',
  'addon.purchased',
  'addon.activated',
  'addon.expired',
  'addon.cancelled',
  'platform.impersonation.started',
  'campus.created',
  'campus.updated',
  'campus.activated',
  'campus.deactivated',
  'campus.archived',
  'campus.deleted',
  'campus.main_changed',
  'campus.users.changed',
  'campus.setup.copied',
  'admission.inquiry.created',
  'admission.inquiry.assigned',
  'admission.inquiry.stage_changed',
  'admission.inquiry.lost',
  'admission.followup.scheduled',
  'admission.followup.due',
  'admission.demo.scheduled',
  'admission.application.submitted',
  'admission.application.documents_requested',
  'admission.application.test_scheduled',
  'admission.application.interview_scheduled',
  'admission.application.approved',
  'admission.application.waitlisted',
  'admission.application.rejected',
  'admission.application.withdrawn',
  'admission.application.fee_paid',
  'admission.application.enrolled',
  'student.admitted',
  'student.enrolled',
  'student.enrollment.ended',
  'student.updated',
  'student.status_changed',
  'student.withdrawn',
  'student.deleted',
  'student.guardian.linked',
  'student.guardian.unlinked',
  'student.promoted',
  'student.detained',
  'student.document.uploaded',
  'student.document.verified',
  'student.note.shared',
  'student.transfer.requested',
  'student.transfer.approved',
  'student.transfer.rejected',
  'student.import.completed',
  'teacher.import.completed',
  'staff.import.completed',
  'student.birthday',
  'staff.birthday',
  'staff.work_anniversary',
  'teacher.created',
  'teacher.updated',
  'teacher.status_changed',
  'teacher.deleted',
  'teacher.subjects.changed',
  'teacher.batch.assigned',
  'teacher.batch.unassigned',
  'teacher.document.uploaded',
  'staff.document.uploaded',
  'staff.document.verified',
  'staff.document.expiring',
  'staff.created',
  'staff.updated',
  'staff.status_changed',
  'staff.position_changed',
  'staff.transferred',
  'staff.exit.recorded',
  'staff.exited',
  'staff.deleted',

  // Academic Events
  'attendance.marked',
  'attendance.updated',
  'attendance.session.locked',
  'attendance.session.unlocked',
  'student.absent',
  'student.late',
  'student.attendance.low',
  'staff.checked_in',
  'staff.checked_out',
  'staff.absent',
  'attendance.import.completed',
  'leave.request.submitted',
  'leave.approval.pending',
  'leave.request.approved',
  'leave.request.rejected',
  'leave.request.cancelled',
  'leave.balance.allocated',
  'leave.balance.adjusted',
  'student.leave.requested',
  'student.leave.approved',
  'student.leave.rejected',
  'student.leave.cancelled',
  'academic_year.activated',
  'academic_year.closed',
  'batch.created',
  'batch.status_changed',
  'enrollment.created',
  'enrollment.withdrawn',
  'enrollment.promoted',
  'enrollment.detained',
  'holiday.declared',
  'calendar.event.published',
  'calendar.event.updated',
  'ptm.booking.created',
  'ptm.booking.cancelled',
  'timetable.updated',
  'substitution.assigned',
  'substitution.cancelled',
  'class.session.scheduled',
  'class.session.cancelled',
  'class.session.rescheduled',
  'class.session.completed',
  'subject.created',
  'subject.archived',
  'curriculum.updated',
  'subject.teacher.assigned',
  'subject.teacher.unassigned',
  'homework.published',
  'homework.updated',
  'homework.cancelled',
  'homework.closed',
  'homework.reminder.sent',
  'homework.submitted',
  'homework.resubmitted',
  'homework.graded',
  'homework.resubmit_requested',
  'study_material.published',
  'exam.schedule.published',
  'exam.cancelled',
  'exam.marks_entry.opened',
  'exam.marks.submitted',
  'exam.marks.verified',
  'exam.marks.reopened',
  'exam.results.published',
  'exam.results.unpublished',
  'exam.reevaluation.requested',
  'exam.reevaluation.fee_pending',
  'exam.reevaluation.resolved',
  'exam.reevaluation.rejected',
  'exam.marks.import.completed',
  'reportcard.generated',
  'reportcard.regenerated',
  'reportcard.published',
  'reportcard.withheld',
  'reportcard.generation.failed',

  // Finance, Portal and Communication Events
  'fee.structure.assigned',
  'fee.invoices.generated',
  'fee.invoice.issued',
  'fee.invoice.due_soon',
  'fee.invoice.due_today',
  'fee.invoice.overdue',
  'fee.reminder.sent',
  'fee.late_fee.applied',
  'fee.invoice.paid',
  'fee.invoice.cancelled',
  'fee.invoice.written_off',
  'fee.invoice.carried_forward',
  'fee.adjustment.requested',
  'fee.adjustment.approved',
  'fee.adjustment.rejected',
  'payment.order.created',
  'payment.link.sent',
  'payment.captured',
  'receipt.issued',
  'payment.failed',
  'payment.cancelled',
  'payment.disputed',
  'payment.cheque.cleared',
  'payment.cheque.bounced',
  'receipt.cancelled',
  'refund.requested',
  'refund.approved',
  'refund.rejected',
  'refund.processed',
  'refund.failed',
  'settlement.reconciled',
  'settlement.mismatch',
  'dayclose.submitted',
  'dayclose.discrepancy',
  'discount.requested',
  'discount.approved',
  'discount.rejected',
  'discount.revoked',
  'scholarship.opened',
  'scholarship.closed',
  'scholarship.application.submitted',
  'scholarship.application.shortlisted',
  'scholarship.application.approved',
  'scholarship.application.rejected',
  'scholarship.awarded',
  'scholarship.disbursed',
  'scholarship.disbursement.reversed',
  'scholarship.award.suspended',
  'scholarship.award.reinstated',
  'scholarship.award.revoked',
  'scholarship.award.renewed',
  'portal.parent.first_login',
  'portal.student.first_login',
  'consent.granted',
  'consent.withdrawn',
  'announcement.acknowledged',
  'certificate.requested',
  'notification.created',
  'announcement.scheduled',
  'announcement.sent',
  'announcement.cancelled',
  'message.queued',
  'message.sent',
  'message.delivered',
  'message.read',
  'message.failed',
  'message.fallback_triggered',
  'whatsapp.account.connected',
  'whatsapp.account.disconnected',
  'whatsapp.account.quality_changed',
  'whatsapp.template.approved',
  'whatsapp.template.rejected',
  'whatsapp.template.paused',
  'whatsapp.message.received',
  'whatsapp.opt_in.recorded',
  'whatsapp.opt_out.recorded',
  'whatsapp.wallet.topped_up',
  'whatsapp.wallet.low_balance',
  'whatsapp.wallet.exhausted',
  'sms.wallet.topped_up',
  'sms.wallet.low_balance',
  'sms.wallet.exhausted',
  'email.identity.verified',
  'email.identity.failed',
  'sms.sender.verified',
  'sms.sender.failed',
  'email.bounced',
  'email.complained',
  'email.unsubscribed',
  'email.suppression.added',
  'email.suppression.removed',
  'sms.dlt_template.approved',
  'sms.dlt_template.rejected',
  'sms.opted_out',

  // Operations and Intelligence Events
  'library.book.issued',
  'library.book.renewed',
  'library.book.returned',
  'library.book.due_soon',
  'library.book.overdue',
  'library.book.lost',
  'library.fine.charged',
  'library.fine.waived',
  'library.import.completed',
  'library.reservation.placed',
  'library.reservation.ready',
  'library.reservation.expired',
  'library.reservation.cancelled',
  'inventory.stock.low',
  'inventory.stock.received',
  'inventory.stock.issued',
  'inventory.stock.returned',
  'inventory.stock.sold',
  'inventory.stock.transferred',
  'inventory.stock.adjusted',
  'inventory.purchase_order.submitted',
  'inventory.purchase_order.approved',
  'inventory.purchase_order.rejected',
  'inventory.purchase_order.ordered',
  'inventory.purchase_order.cancelled',
  'inventory.asset.assigned',
  'inventory.asset.returned',
  'inventory.asset.overdue',
  'inventory.import.completed',
  'transport.assignment.created',
  'transport.assignment.changed',
  'transport.assignment.suspended',
  'transport.assignment.resumed',
  'transport.assignment.ended',
  'transport.trip.started',
  'transport.trip.completed',
  'transport.trip.cancelled',
  'transport.student.boarded',
  'transport.student.not_boarded',
  'transport.student.dropped',
  'transport.vehicle.document_expiring',
  'transport.driver.licence_expiring',
  'transport.maintenance.due',
  'hostel.allocation.reserved',
  'hostel.allocation.checked_in',
  'hostel.allocation.transferred',
  'hostel.allocation.vacated',
  'hostel.allocation.cancelled',
  'hostel.attendance.marked',
  'hostel.student.absent',
  'hostel.student.late_entry',
  'hostel.leave.requested',
  'hostel.leave.approved',
  'hostel.leave.rejected',
  'hostel.leave.cancelled',
  'hostel.leave.checked_out',
  'hostel.leave.returned',
  'hostel.leave.overdue',
  'hostel.visitor.checked_in',
  'hostel.visitor.checked_out',
  'payroll.salary.revised',
  'payroll.adjustment.approved',
  'payroll.adjustment.rejected',
  'payroll.run.processed',
  'payroll.run.process_failed',
  'payroll.run.approved',
  'payroll.run.reopened',
  'payroll.run.paid',
  'payroll.run.locked',
  'payroll.payslip.published',
  'payroll.payslip.held',
  'payroll.payslip.cancelled',
  'payroll.loan.requested',
  'payroll.loan.approved',
  'payroll.loan.rejected',
  'payroll.loan.disbursed',
  'payroll.loan.closed',
  'payroll.tax_declaration.submitted',
  'payroll.tax_declaration.verified',
  'certificate.request.submitted',
  'certificate.request.approved',
  'certificate.request.rejected',
  'certificate.request.cancelled',
  'certificate.issued',
  'certificate.reissued',
  'certificate.revoked',
  'certificate.sent',
  'certificate.bulk_issue.completed',
  'certificate.verified',
  'analytics.report.saved',
  'analytics.report.shared',
  'analytics.schedule.created',
  'analytics.schedule.delivered',
  'analytics.schedule.failed',
  'analytics.snapshot.computed',
  'analytics.snapshot.rebuilt',
  'ai.insight.generated',
  'ai.insight.critical',
  'ai.insight.acted',
  'ai.insight.dismissed',
  'ai.student.risk_level_changed',
  'ai.risk_scores.computed',
  'ai.quota.threshold_reached',
  'ai.quota.exhausted',
  'settings.updated',
  'settings.branding.updated',
  'settings.number_sequence.updated',
  'settings.custom_field.created',
  'settings.custom_field.archived',
  'payment_gateway.connected',
  'payment_gateway.verification_failed',
  'payment_gateway.disconnected',
  'api_key.created',
  'api_key.rotated',
  'api_key.revoked',
  'api_key.expiring',
  'policy.published',
  'consent.requested',
  'dsr.received',
  'dsr.due_soon',
  'dsr.completed',
  'dsr.rejected',
  'data_breach.reported',
  'data_breach.notification_due',
  'data_breach.closed',
  'file.uploaded',
  'file.quarantined',
  'file.deleted',
  'import.started',
  'import.completed',
  'import.completed_with_errors',
  'import.failed',
  'export.completed',
  'export.failed',
  'audit.chain.mismatch',
] as const;

/** The union of every event name. A handler can only subscribe to a name that exists. */
export type DomainEventName = (typeof DOMAIN_EVENTS)[number];

const DOMAIN_EVENT_SET: ReadonlySet<string> = new Set<string>(DOMAIN_EVENTS);

/** Narrows a name read from the outbox table or a webhook before it is dispatched. */
export function isDomainEventName(value: string): value is DomainEventName {
  return DOMAIN_EVENT_SET.has(value);
}

// The rule in the chapter is two or three segments. The catalog holds one four-segment name,
// `exam.marks.import.completed`, and a name is permanent once published, so four is the limit.
export const EVENT_NAME_PATTERN = /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*){1,3}$/;

/** True when a proposed name follows the rule: dotted, lower case, at most 80 characters. */
export function isValidEventName(value: string): boolean {
  return value.length <= 80 && EVENT_NAME_PATTERN.test(value);
}

/** The module or aggregate that owns the event: the `fee` in `fee.invoice.paid`. */
export function eventDomain(name: DomainEventName): string {
  const separator = name.indexOf('.');
  return separator === -1 ? name : name.slice(0, separator);
}

/** Who caused an event. `SYSTEM` covers scheduled jobs and webhook callbacks. */
export type EventActorType = 'USER' | 'SYSTEM' | 'API_KEY' | 'IMPERSONATION';

export interface EventActor {
  type: EventActorType;
  id: string | null;
  role?: string;
  name?: string;
}

/** The Prisma model a fact is about, plus its id. */
export interface EventEntity {
  type: string;
  id: string;
}

/**
 * The outer shape every event shares. Only `payload` differs, and it carries identifiers plus
 * a few labels, never a whole record. Money inside a payload is a string, dates are UTC.
 */
export interface DomainEvent<TPayload = Record<string, unknown>> {
  id: string;
  name: DomainEventName;
  version: number;
  occurredAt: string;
  organizationId: string | null;
  campusId?: string | null;
  actor: EventActor;
  entity: EventEntity;
  payload: TPayload;
  requestId?: string;
  correlationId?: string;
}

/** The queues named in the background jobs chapter, for typed producers and workers. */
export const QUEUE_NAMES = [
  'notifications',
  'whatsapp',
  'sms',
  'email',
  'pdf',
  'imports',
  'exports',
  'invoices',
  'reminders',
  'snapshots',
  'webhooks',
  'ai',
] as const;

export type QueueName = (typeof QUEUE_NAMES)[number];
